version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.2.1"

    steps:
      - checkout

      # Build the app and run tests
      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone Xs Max
            SCAN_SCHEME: TDD

workflows:
  version: 2
  workflow:
    jobs:
    - build